pub static LA_LIGA_GOALS: u32 = 43;
pub static CHAMPIONS_LEAGUE_GOALS: u32 = 10;
pub static COPA_DEL_REY_GOALS: u32 = 5;

pub static TOTAL_GOALS: u32 = LA_LIGA_GOALS + CHAMPIONS_LEAGUE_GOALS + CHAMPIONS_LEAGUE_GOALS;
